baseURL = "http://proto.bulletprooftoupee.com/"
languageCode = "en-us"
title = "bulletprooftoupee"
theme="blank"
#defaultLayout="posts"

#sectionPagesMenu = "main"

[params]
  author="Ricardo Galvez"
  subtitle="Projects, Creative Works and Writings of Ricardo E. Galvez"
  # Make an image post
  postimage = ""
    postimagealt = ""
  figcaption = ""

[permalinks]
    post = "/:year/:month/:title/"

[menus]
    [[menu.main]]
        identifier = "blog"
        name = "web-log"
        title = "the blog section"
        url = "/posts/"
        weight = -110
    [[menu.main]]
        identifier = "experiments"
        name = "experiments"
        title = "experiments title"
        url = "/experiments/"
        weight = -100
    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        title = "portfolio"
        url = "/portfolio/"
        weight = 1