baseURL = "http://bulletprooftoupee.com/"
languageCode = "en-us"
title = "bulletprooftoupee"
theme="blank"
#defaultLayout="posts"

sectionPagesMenu = "main"

[params]
  author="Ricardo Galvez"
  subtitle="Projects, Creative Works and Writings of Ricardo E. Galvez"

[permalinks]
    post = "/:year/:month/:title/"
