baseURL = "http://proto.bulletprooftoupee.com/"
languageCode = "en-us"
title = "bulletprooftoupee.com"
theme="blank"
relativeURLs="true"
#defaultLayout="posts"

#sectionPagesMenu = "main"

[params]
    cdnURL = "http://cdn.bulletprooftoupee.com/"
    author="Ricardo Eric Galvez"
    subtitle="Creative Works of Ricardo E. Galvez"
    # Image params:
    postimage1x = ""
    postimage2x = ""
    postimage3x = ""
    postimagealt = ""
    # the figure catption param:
    figcaption = ""
    # svg clip path classes (for declaring the path and setting a color):
    svgClipObjectClass = ""
    svgColorClass = ""
    # portfolio landing page image param:
    portfolioHero = ""
    portfolioHeroAlt = ""
    # some classes we want to expose to hugo:
    [params.classes]
        homePage = "home-page"
        innerPage = "inner-page"
    [params.libraries]
        matterJS = "js/vendor/matter/matter.min.js"
        paperJS = "js/vendor/paper/paper-full.min.js"
        p5JS = "js/vendor/p5/p5.js"
        threeJS = "js/vendor/three.min.js"

[permalinks]
    post = "/:year/:month/:title/"

[menus]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        title = "the blog section"
        url = "/posts/"
        weight = 5
    [[menu.main]]
        identifier = "experiments"
        name = "experiments"
        title = "experiments"
        url = "/experiments/"
        weight = -10
    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        title = "portfolio"
        url = "/portfolio/"
        weight = 1