baseURL = "http://proto.bulletprooftoupee.com/"
languageCode = "en-us"
title = "bulletprooftoupee.com"
theme="blank"
relativeURLs="true"
#defaultLayout="posts"

#sectionPagesMenu = "main"



[params]
    cdnURL = "http://cdn.bulletprooftoupee.com/"
    author="Ricardo Eric Galvez"
    subtitle="Creative Works of Ricardo E. Galvez"
    # Image params:
    postimage1x = ""
    postimage2x = ""
    postimage3x = ""
    postimagealt = ""
    # the figure catption param:
    figcaption = ""
    # svg source and clip path classes (for declaring the path and setting a color):
    svgSource = ""
    svgClipObjectClass = ""
    svgColorClass = ""
    # portfolio landing page image param:
    portfolioHero1x = ""
    portfolioHero2x = ""
    portfolioHero3x = ""
    portfolioHeroAlt = ""
    # some classes we want to expose to hugo:
    vendorPath = "js/vendor/"
    [params.classes]
        homePage = "home-page"
        innerPage = "inner-page"
    [params.vendors]
        matterJS = "matter/matter.min.js"
        paperJS = "paper/paper-full.js"
        p5JS = "p5/p5.js"
        svgJS = "svg/svg.min.js"
        threeJS = "three/three.min.js"
        gsapJS = "gsap/TweenMax.min.js"

[permalinks]
    post = "/:year/:month/:title/"

[menus]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        title = "the blog section"
        url = "/posts/"
        weight = 5
    [[menu.main]]
        identifier = "experiments"
        name = "experiments"
        title = "experiments"
        url = "/experiments/"
        weight = -10
    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        title = "portfolio"
        url = "/portfolio/"
        weight = 1

[resources]