baseURL = "http://bulletprooftoupee.com/"
languageCode = "en-us"
title = "bulletprooftoupee"
theme="blank"
#defaultLayout="posts"

sectionPagesMenu = "main"

[params]
  author="Ricardo Galvez"
  subtitle="we run the rondo"
